[package]
name = "mcp-example"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
autoagents-derive.workspace = true
autoagents = { workspace = true, features = ["openai", "logging"] }
autoagents-toolkit = { workspace = true, features = ["mcp"] }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio-stream.workspace = true
env_logger.workspace = true
